version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      - MONGODB_URL=mongodb+srv://kavindakiridena:UsGGXH0OjoB3oHDJ@cluster0.xlrfs.mongodb.net/products?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5555
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
